import type { GameCapabilityMetadata } from './types'

export const GAME_CAPABILITIES: Record<string, GameCapabilityMetadata> = {
  // ── Main arena missions ──────────────────────────────────────────────────
  SPEED: {
    gameId: 'SPEED', name: 'سرعت بهسازانی',
    minPlayers: 2, maxPlayers: 8,
    supportsSinglePlayer: false, supportsOnline: true, supportsRoomCode: true,
    supportsHiddenRoles: false, supportsPrivateInformation: false,
    supportsTeams: false, requiresHost: true, requiresRealtimeSync: true,
    winConditions: ['بیشترین امتیاز'],
  },
  MEMORY: {
    gameId: 'MEMORY', name: 'حافظه بهسازانی',
    minPlayers: 1, maxPlayers: 8,
    supportsSinglePlayer: true, supportsOnline: false, supportsRoomCode: false,
    supportsHiddenRoles: false, supportsPrivateInformation: false,
    supportsTeams: false, requiresHost: false, requiresRealtimeSync: false,
    winConditions: ['حداکثر تطابق'],
  },
  LOGIC: {
    gameId: 'LOGIC', name: 'منطق بهسازانی',
    minPlayers: 2, maxPlayers: 8,
    supportsSinglePlayer: false, supportsOnline: true, supportsRoomCode: true,
    supportsHiddenRoles: false, supportsPrivateInformation: false,
    supportsTeams: false, requiresHost: true, requiresRealtimeSync: true,
    winConditions: ['بیشترین پاسخ درست'],
  },
  FASTEST: {
    gameId: 'FASTEST', name: 'سریع‌ترین انگشت',
    minPlayers: 2, maxPlayers: 8,
    supportsSinglePlayer: false, supportsOnline: true, supportsRoomCode: true,
    supportsHiddenRoles: false, supportsPrivateInformation: false,
    supportsTeams: false, requiresHost: true, requiresRealtimeSync: true,
    winConditions: ['اول پاسخ دادن'],
  },
  TEAM: {
    gameId: 'TEAM', name: 'چشمک',
    minPlayers: 4, maxPlayers: 8,
    supportsSinglePlayer: false, supportsOnline: true, supportsRoomCode: true,
    supportsHiddenRoles: true, supportsPrivateInformation: true,
    supportsTeams: true, requiresHost: true, requiresRealtimeSync: true,
    roles: ['بازیکن', 'عامل مخفی'],
    winConditions: ['تیم با بیشترین چشمک'],
  },
  FINAL: {
    gameId: 'FINAL', name: 'نبرد قلمرو',
    minPlayers: 2, maxPlayers: 8,
    supportsSinglePlayer: false, supportsOnline: true, supportsRoomCode: true,
    supportsHiddenRoles: false, supportsPrivateInformation: false,
    supportsTeams: false, requiresHost: true, requiresRealtimeSync: true,
    winConditions: ['بیشترین قلمرو'],
  },
  NAME_FAMILY: {
    gameId: 'NAME_FAMILY', name: 'اسم‌فامیل',
    minPlayers: 2, maxPlayers: 8,
    supportsSinglePlayer: false, supportsOnline: true, supportsRoomCode: true,
    supportsHiddenRoles: false, supportsPrivateInformation: false,
    supportsTeams: false, requiresHost: true, requiresRealtimeSync: true,
    winConditions: ['بیشترین امتیاز'],
  },
  ONE_WORD: {
    gameId: 'ONE_WORD', name: 'یک کلمه، چند سرنخ',
    minPlayers: 2, maxPlayers: 8,
    supportsSinglePlayer: false, supportsOnline: true, supportsRoomCode: true,
    supportsHiddenRoles: false, supportsPrivateInformation: true,
    supportsTeams: false, requiresHost: true, requiresRealtimeSync: true,
    winConditions: ['بیشترین حدس درست'],
  },

  // ── Behsazani games ──────────────────────────────────────────────────────
  behsazani_mafia: {
    gameId: 'behsazani_mafia', name: 'مافیای بهسازانی',
    minPlayers: 4, maxPlayers: 16,
    supportsSinglePlayer: false, supportsOnline: true, supportsRoomCode: true,
    supportsHiddenRoles: true, supportsPrivateInformation: true,
    supportsTeams: true, requiresHost: true, requiresRealtimeSync: true,
    roles: ['شهروند', 'مافیا', 'رئیس مافیا', 'کارآگاه', 'دکتر'],
    winConditions: ['حذف همه مافیا', 'مافیا برابر یا بیشتر از شهروندان'],
  },
  behsazani_spy: {
    gameId: 'behsazani_spy', name: 'جاسوس',
    minPlayers: 3, maxPlayers: 10,
    supportsSinglePlayer: false, supportsOnline: true, supportsRoomCode: true,
    supportsHiddenRoles: true, supportsPrivateInformation: true,
    supportsTeams: false, requiresHost: true, requiresRealtimeSync: true,
    roles: ['کارمند', 'جاسوس'],
    winConditions: ['شناسایی جاسوس', 'جاسوس مکان را حدس می‌زند'],
  },
  behsazani_project_council: {
    gameId: 'behsazani_project_council', name: 'شورای پروژه',
    minPlayers: 5, maxPlayers: 10,
    supportsSinglePlayer: false, supportsOnline: true, supportsRoomCode: true,
    supportsHiddenRoles: true, supportsPrivateInformation: true,
    supportsTeams: true, requiresHost: true, requiresRealtimeSync: true,
    roles: ['کارمند', 'خرابکار'],
    winConditions: ['۳ مأموریت موفق', '۳ مأموریت شکست'],
  },
  behsazani_code_breakers: {
    gameId: 'behsazani_code_breakers', name: 'رمزگشایان',
    minPlayers: 4, maxPlayers: 8,
    supportsSinglePlayer: false, supportsOnline: true, supportsRoomCode: true,
    supportsHiddenRoles: false, supportsPrivateInformation: true,
    supportsTeams: true, requiresHost: true, requiresRealtimeSync: true,
    roles: ['رمزگذار', 'بازیکن'],
    winConditions: ['یافتن همه کلمات تیم'],
  },
  behsazani_project_code: {
    gameId: 'behsazani_project_code', name: 'رمز پروژه',
    minPlayers: 4, maxPlayers: 8,
    supportsSinglePlayer: false, supportsOnline: true, supportsRoomCode: true,
    supportsHiddenRoles: false, supportsPrivateInformation: true,
    supportsTeams: true, requiresHost: true, requiresRealtimeSync: true,
    roles: ['رمزگذار', 'رمزشکن'],
    winConditions: ['کشف کد مخفی'],
  },
  behsazani_one_word: {
    gameId: 'behsazani_one_word', name: 'یک کلمه',
    minPlayers: 3, maxPlayers: 8,
    supportsSinglePlayer: false, supportsOnline: true, supportsRoomCode: true,
    supportsHiddenRoles: false, supportsPrivateInformation: true,
    supportsTeams: false, requiresHost: true, requiresRealtimeSync: true,
    roles: ['حدس‌زننده', 'سرنخ‌دهنده'],
    winConditions: ['بیشترین حدس درست'],
  },
  behsazani_anonymous_drawer: {
    gameId: 'behsazani_anonymous_drawer', name: 'طراح ناشناس',
    minPlayers: 3, maxPlayers: 8,
    supportsSinglePlayer: false, supportsOnline: false, supportsRoomCode: false,
    supportsHiddenRoles: false, supportsPrivateInformation: true,
    supportsTeams: false, requiresHost: true, requiresRealtimeSync: false,
    roles: ['طراح', 'حدس‌زننده'],
    winConditions: ['بیشترین حدس سریع'],
  },
  behsazani_it_quiz: {
    gameId: 'behsazani_it_quiz', name: 'مسابقه بزرگ IT',
    minPlayers: 2, maxPlayers: 12,
    supportsSinglePlayer: false, supportsOnline: true, supportsRoomCode: true,
    supportsHiddenRoles: false, supportsPrivateInformation: false,
    supportsTeams: false, requiresHost: true, requiresRealtimeSync: true,
    winConditions: ['بیشترین امتیاز'],
  },
  hide_seek: {
    gameId: 'hide_seek', name: 'قایم‌باشک',
    minPlayers: 1, maxPlayers: 1,
    supportsSinglePlayer: true, supportsOnline: false, supportsRoomCode: false,
    supportsHiddenRoles: false, supportsPrivateInformation: false,
    supportsTeams: false, requiresHost: false, requiresRealtimeSync: false,
    winConditions: ['پیدا کردن همه'],
  },
  behsazan_hunt: {
    gameId: 'behsazan_hunt', name: 'شکار بهسازانی',
    minPlayers: 1, maxPlayers: 1,
    supportsSinglePlayer: true, supportsOnline: false, supportsRoomCode: false,
    supportsHiddenRoles: false, supportsPrivateInformation: false,
    supportsTeams: false, requiresHost: false, requiresRealtimeSync: false,
    winConditions: ['بیشترین شکار'],
  },
}

export function getGameCapabilities(gameId: string): GameCapabilityMetadata | undefined {
  return GAME_CAPABILITIES[gameId]
}
